---
name: prek

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prek:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      # prek の terraform-fmt 用
      - uses: jdx/mise-action@v3.5.1
        with:
          version: 2025.9.13
          cache: true
          install: false

      - name: Install tools with mise
        run: mise install
        env:
          MISE_NODE_VERIFY: none

      # Install pnpm dependencies
      - name: Install dependencies
        run: pnpm install

      # Run prek with official action
      - uses: j178/prek-action@v1
        with:
          extra_args: --all-files
